### ISSUE TITLE
TableFootnoteRef not superscripted in OGC Abstract Specification HTML

### ISSUE THREAD

**Issue by ccrook** [metanorma/metanorma#304]
In the OGC Abstract Specification table footnotes are styled with 

```css
a.TableFootnoteRef + a.TableFootnoteRef:before {
  content: ", ";
  vertical-align: super; }
```
I am not clear what the intention of this is.  (The CSS reference at https://www.w3schools.com/cssref/css_selectors.php suggests that the selector should be ::before rather than :before).  However it does not appear to be identifying table footnotes created with footnote:[...].  The result is that the footnote appears as normal text, eg

```
| logarithmfootnote:log10[Base 10 logarithm] | 
```
is displayed as _logarithma_ rather than _logarithm<sup>a</sup>_.

I think it would be more consistent with the PDF to instead use CSS 

```css
a.TableFootnoteRef, span.TableFootnoteRef {
  vertical-align: super; }
```

which results in a superscript in both the reference and the footnote itself.
