### ISSUE TITLE
Incorrect link when generate metanorma colletion with single source file

### ISSUE THREAD

**Issue by kwkwan** [metanorma/metanorma#360]
When generate metanorma colletion (`bundle exec metanorma collection collection.yml -x xml,html,presentation -w documents/output -c cover.html`) with single source file (e.g. `iso-10303-56`), the link in the index.html is incorrect.

The sample collection.yml looks like:
```
---
directives:
- documents-inline
bibdata:
  title:
  - language: en
    content: Industrial automation systems and integration -- Product data representation
      and exchange -- Integrated generic resource
  docid:
    type: iso
    id: '10303'
  edition: '7'
  copyright:
    owner:
      name: International Standards Organization
      abbreviation: ISO
    from: '2021'
manifest:
  level: collection
  title: ISO collection
  manifest:
  - level: document
    title: Document
    docref:
    - fileref: documents/iso-10303-56/document.xml
      identifier: iso10303-56
      sectionsplit: true
  - level: attachments
    title: Attachments
    docref:
    - fileref: schemas/resources/state_type_schema/state_type_schema.exp
      identifier: state_type_schema.exp
      attachment: true
    - fileref: schemas/resources/state_observed_schema/state_observed_schema.exp
      identifier: state_observed_schema.exp
      attachment: true
    - fileref: documents/iso-10303-56/sections/schemadocs/state_type_schema.html
      identifier: state_type_schema.html
      attachment: true
    - fileref: documents/iso-10303-56/sections/schemadocs/state_observed_schema.html
      identifier: state_observed_schema.html
      attachment: true
```

<img width="1549" alt="Screenshot 2024-03-13 at 5 08 52 PM" src="https://github.com/metanorma/metanorma/assets/29566367/dc3abe72-eaee-4f53-ba47-bb2c6b97dcbc">

The link should point to `xxx_index.html` instead of `index.html`.

When the source files is more than one, the linkage is correct!
