### ISSUE TITLE
Interleave documents and manifests within document collection manifests

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma#375]
In collection manifests to date, manifests can contain lists of documents, docref, and recursively nested manifests:

````
manifest:
   title: ...
   docref:
      - fileref: ...
      - fileref: ...
   manifest:
       title: ...
       docref:
         - fileref: ...
         - fileref: ...
````

In this implementation, manifests and docrefs are separate: there's a list of documents, and there is a list of recursive manifests.

https://github.com/metanorma/iso-10303-srl/issues/41 has raised the requirement that manifests be interleaved with docrefs: a document can be broken up into other documents, but be part of an overall tree, giving rise to an index like:

> * ISO-10303-41
>   * action-schema
>   * application_context_schema
> ....
> * ISO-10303-42

This is not what we designed for, but we need the ability to organise documents in trees like that. This will also be how we realise subfolders in collections, but that can wait.

The least disruptive way to do this is to make docref contain either manifest or fileref, mutually exclusive. So:

````
manifest:
   title: ...
   docref:
      - fileref: ...
      - manifest:
         title: ...
         docref:
           - fileref: ...
           - fileref: ...
      - fileref: ...
````
