### ISSUE TITLE
Collection attachments not resolved and linked in HTML (ISO 10303 "Computer interpretable listings")

### ISSUE THREAD

**Issue by kwkwan** [metanorma/metanorma#382]
There are no attachments in the html in section `Computer interpretable listings`.

<img width="1556" alt="Screenshot 2024-05-08 at 12 23 31 PM" src="https://github.com/metanorma/metanorma/assets/29566367/d7b8ec43-67ef-4a29-b214-070dc7348a6e">

**Comment by ronaldtse** [comment]
The way to compile this document is:

```sh
$ cd iso-10303-srl
$ bundle exec metanorma documents/iso-10303-1064/collection.yml
```

**Comment by manuelfuenmayor** [comment]
I get error by doing this:
```
$ bundle exec metanorma documents/iso-10303-1064/collection.yml
[metanorma] Error: Please specify a standard type: [:standoc, :iso, :iec, :ieee, :ietf, :generic, :bipm, :cc, :csa, :iho, :jis, :un, :ogc, :itu].
```

I also tried this:
```
$ bundle exec metanorma -t iso documents/iso-10303-1064/collection.yml
[metanorma] Error: file extension .yml is not supported.

```

**Comment by ronaldtse** [comment]
@kwkwan please address @manuelfuenmayor 's comment.

His command is supposed to work, right? Thanks.

**Comment by kwkwan** [comment]
If you just want to generate a collection for a single part, say, part 1064, you can edit the `collection-test.yml` like the lines shown below.
```
---
directives:
- documents-inline
bibdata:
  title:
  - language: en
    content: Industrial automation systems and integration -- Product data representation
      and exchange
  docid:
    type: iso
    id: '10303'
  edition: 12
  copyright:
    owner:
      name: International Standards Organization
      abbreviation: ISO
    from: '2024'
manifest:
  level: collection
  title: STEP Resources Library (SRL)
  sectionsplit: true
  docref:
  - file: documents/iso-10303-1064/collection.yml
```
and then run
```
bundle exec collection.rb -ymetanorma-test.yml
```
