### ISSUE TITLE
Simplify manifests

### ISSUE THREAD

**Issue by opoudjis** [metanorma/metanorma#383]
The ongoing work around ISO 10303, and the concern to make manifests easier for users to populate (surfaced in https://github.com/metanorma/metanorma-cli/issues/328 ) are forcing simplification on manifest processing and manifest format. Manifests are also currently implemented in an inflexible fashion that is not coping with these requests for change.

Manifests currently have the following grammar:

````
/* representation of a collection */
manifest: level?, title?, docref*, manifest* 

/* representation of a collection entry */
docref: fileref, identifier, url?, attachment?, sectionsplit?, index?, presentation-xml?, manifest*

level, title, identifier: text

fileref: URI (local)

url: URI (local or global)

/* flags: 
attachment: this is an attachment, do not parse
sectionsplit: break this document up, one HTML page per clause
index: exclude this document from the generated collection index
presentation-xml: this document is already Presentation XML, do not generate Presentation XML from Semantic XML
*/
attachment, sectionsplit, index, presentation-xml: boolean
````

Things that need to change:

* Originally, we had manifest/manifest to represent the recursive nesting of collections. But that did not allow us to interleave single documents with subcollections in the index, which is a genuine requirement of collections, as implemented in https://github.com/metanorma/metanorma/issues/375 . We now have two ways of recursing collections, manifest/manifest, and manifest/docref/manifest. And manifest/manifest is obsolete.
* Changes @ronaldtse has independently been introducing to the collection involve docref pointing to collection manifest YAML files. That is in fact equivalent to manifest/docref/manifest anyway.
* level was originally intended as a title of the type of subcollection being given, and as a mechanism of segregating attachments from documents. That is an inflexible requirement, and no actual code hinges on it anyway.
* presentation-xml can be inferred from the filename.
* Ronald wants identifier inferred from the file contents, if this is already a Metanorma XML file.
* Ronald wants the separation between docref and manifest to go away.

This is the new proposed simpler structure. I am going to use aliases to maintain some backward compatibility:

````
manifest: type?, title?, entry*, identifier?, url?, attachment?, sectionsplit?, index?

entry: file_entry | manifest_entry

file_entry: file

manifest_entry: manifest
````

with aliases:

* level => type
* docref => entry
* fileref => file
* presentation-xml: inferred from file or from type

file is the key in a terminal node; entry is the key in a non-terminal node; in RNC:

````
manifest = element manifest { Manifest }

Manifest = type?, title?, entry*, identifier?, url?, attachment?, sectionsplit?, index?

entry = file_entry | manifest_entry

file_entry = element file { text }

manifest_entry = element entry { Manifest }
````

So the only difference between a file description and a collection description under `entry` is that the file description has a `file` key, and the collection description has its own `entry` key with further nested descriptions. Any entry can have any of the attributes: an identifier, a title, a type, a URL, an attachment status. In the case of file-specific attributes, like index and sectionsplit, they can be inherited from manifest to file entries recursively (and there is code that already does that.) I am going to keep propagating those attributes on parsing from collection nodes down to terminal nodes on initial parsing.

So, before:

````
manifest:
  level: collection
  title: XXX
  manifest:
  - level: document
    title: Document
    docref:
    - fileref: documents/<document-1>/document.xml
      identifier: <document-1>
      sectionsplit: true
    - fileref: documents/<document-2>/document.xml
      identifier: <document-2>
      sectionsplit: true
    - manifest:
      - fileref: documents/<document-3>/document.xml
         identifier: <document-3>
````

After:

````
manifest:
  type: collection
  title: XXX
  sectionsplit: true
  entry:
    - file: documents/<document-1>/document.xml
    - file: documents/<document-2>/document.xml
      identifier: <document-2>
    - type: subcollection
       title: Sub Collection
       entry:
         - file: documents/<document-3>/document.xml
            identifier: <document-3>
````

The processing and population of manifests is moving to Shale, so that XML and YAML can be parsed into a Ruby object, instead of a hash as has been the case hitherto.
