### ISSUE TITLE
Cumbersome to add an attachment to a document, should streamline

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma#410]
Right now we have to do these steps:

1. Add a collection.yml with the details of the attachment
2. Add a bibliography with an anchor and path of the attachment

Both are annoying steps.

These samples are from [iso-10303](https://github.com/metanorma/iso-10303).

## collection.yml

```yaml
directives:
  - documents-inline
bibdata:
  title:
    - language: en
      content: "Industrial automation systems and integration -- Product data representation and exchange -- Integrated application resource: Mesh-based computational fluid dynamics"
    - language: fr
      content: "Systèmes d'automatisation industrielle et intégration -- Représentation et échange de données de produits -- Ressources d'application intégrées: "
  type: collection
  docid:
    type: iso
    id: 10303-110
  edition: 1
  copyright:
    owner:
      name: International Standards Organization
      abbreviation: ISO
    from: 2011
manifest:
  level: collection
  title: ISO Collection
  docref:
    - level: document
      title: Document
      sectionsplit: true
      docref:
        - fileref: document.adoc
    - level: attachments
      title: Attachments
      docref:
        - fileref: ../../plain_schemas/resources/basis_schema/basis_schema.exp
          identifier: basis_schema.exp
          attachment: true
        - fileref: ../../plain_schemas/resources/conditions_schema/conditions_schema.exp
          identifier: conditions_schema.exp
          attachment: true
```

## Bibliography

```adoc

[bibliography]
== Bibliography

* [[[basis_schema.exp,repo:(current-metanorma-collection/basis_schema/basis_schema.exp)]]]
* [[[conditions_schema.exp,repo:(current-metanorma-collection/conditions_schema/conditions_schema.exp)]]]
```

## Proposal

I propose that we have a separate mechanism to streamline this. This is untenable for normal users that do not use automation.

**Comment by opoudjis** [comment]
> I propose that we have a separate mechanism to streamline this. 

You have not proposed anything whatsoever, apart from "separate mechanism", and "annoying", which are meaningless and unactionable. I will not rip out working code and invent something completely new, with no specification, to mollify some unspecified aesthetic compunction. I deal in concrete code.

As https://github.com/metanorma/mn2pdf/issues/278#issuecomment-2351516062 fails to understand, collections are not prerequisites for attachments: an attachment can be specified as only a bibliographic entry in a  single document.

In the case of collections, I am going to enact the following simplification to the existing collection code:

If an attachment is specified in collection.yml in a collection, there is no need to also specify it in the bibliography of any document: given

````
- fileref: ../../plain_schemas/resources/basis_schema/basis_schema.exp
   identifier: basis_schema.exp
   attachment: true
````

I can generate, and append to the bibliography of each document, a bibliographic entry for

````
* [[[basis_schema.exp,repo:(current-metanorma-collection/../../plain_schemas/resources/basis_schema/basis_schema.exp)]]]
````

The actual address within repo:(current-metanorma-collection....) isn't important anyway, the actual location of the file is looked up in the manifest anyway.

In fact, that can extend to all files in the manifest: the bibliographic entries for all the members of the collection can be generated from the manifest, and do not need to be specified separately. (If the identifier for a file is already in the bibliography of a document, of course, it will not be added again.)

That means that, for both single documents and collections, attachments need only be specified once.

**Comment by opoudjis** [comment]
For starters, you do NOT need to specify attachments in the document bibliography at all. If you specify the attachment only in the manifest, it will be copied across to the output directory, and it will be included in the index page. 

So the 

> Right now we have to do these steps:

is uninformed.

The attachment needs only be specified in the bibliography of a document, if it will be cross-referenced in the document. That is an entirely reasonable request: if you're going to cross-reference an external file somewhere, what did you expect the anchor to point to? The moon?

I am going to implement autoinsertion of identifiers from the manifest. In fact, there is no reason to restrict this to attachments: I will do this for any document in a collection.

But there are reasons I want users specifying links explicitly, which this ticket is blithely ignoring.

Cross-references link to anchors, not arbitrary identifiers: if the identifier has no anchor and has just an identifier, I will need to sanitise it. (That includes replacing space with _.) If the user puts an illegal identifier in the manifest, I'm going to crash. If the user stupidly puts spaces in the attachment identifier, I am not going to respect them. If the user puts no identifier for the attachment, and expects something to link to the attachment from the main document, they can pound sand: Metanorma is not a mind-reading app. There are limits to how much food I can chew on a user's behalf.

So if you have:

````
Manifest:

...
  manifest:
    - level: document
      title: Document
      docref:
        - fileref: contrib-660.xml
          identifier: SG17-C660
        - fileref: G.650.1-201803.xml
          identifier: ITU G.650
        - fileref: LICENSE.TXT
          identifier: License A
          attachment: true
````

and you want to link from  SG17-C660 to ITU G.650 and to LICENSE.TXT, I expect you now to do:

````
...
<<ITU_G.650,ITU G.650>>

<<License_A,License A>>

...

[bibliography]
== Bibliography
* [[[ITU_G.650,repo:(current-metanorma-collection/ITU G.650)]]]
* [[[License_A,repo:(current-metanorma-collection/License A)]]]
````

This right now works.

You don't want the user to have to insert the bibliography in the document. You do however want Metanorma to make sense of a `<<ITU G.650>>` when it finds it randomly in a document, by checking it against the manifest.

The documents are compiled standalone first, before being assembled into a collection. You have a cross-reference without a target, if you don't have a bibliography to define the anchor. That compilation will fail, because Metanorma will not know where ITU G.650 is defined at all: it will treat it as an undefined cross-reference within the document. 

To prevent that, I will need to preprocess all Metanorma documents in the collection, inserting into them a bibliography containing all items in the manifest, and then make sure that that inserted bibliography does not collide with any existing items already defined in the collection.

In fact, the easiest way to do this is in preprocessing:

* In update_xrefs(), before I process indirect expressions,
* gather all unresolved anchor cross-references
* gather all collection documents whose identifier matches the unresolved cross-references
* insert a hidden bibliography for those collection documents 
* convert the unresolved cross-references into bibliographic cross-references to that hidden bibliography, which will subsequently be converted into links.

All that rigmarole, to save the user typing

````
[bibliography]
== Bibliography
* [[[License_A,repo:(current-metanorma-collection/License A)]]]
````

Something that they *only* need to do if they are in fact cross-referencing the attachment inside the document, and creating a `<<License A>>` to begin with. I

If they are cross-referencing the attachment, they are already needing to think ahead about it. Just like they do if they are cross-referencing another full document in the collection. They should in fact be thinking about what the targets of their links are. You are wanting a click-and-drool approach to linking to attachments, and that is going to cause problems and not solutions.

I still think this request has not been thought through, and I still need discussion with you @ronaldtse on why this is warranted. Will not action until that time.
