### ISSUE TITLE
Collection compilation: fail early if bibdata incorrect instead of after compiling documents

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma#416]
I was creating a collection.yml file for PLATEAU 001 and 002.

```yaml
directives:
  - documents-inline
bibdata:
  title:
    - language: en
      content: "Project PLATEAU standards"
    - language: jp
      content: "Project PLATEAU standards"
  type: collection
  docid:
    type: handbook
    id: "PLATEAU H999"
  edition: 1
  copyright:
    owner:
      name: MLIT Project PLATEAU
      abbreviation: MLIT
    from: 2024
manifest:
  level: collection
  title: Project PLATEAU Collection
  docref:
    - level: document
      title: 001
      sectionsplit: true
      docref:
        - fileref: sources/001-v4/document.adoc
    - level: document
      title: 002
      sectionsplit: true
      docref:
        - fileref: sources/002-v4/document.adoc
```

This portion was a problem:

```yaml
  docid:
    type: handbook
```

After many many minutes this error showed up:

```
$ bundle exec metanorma collection collection.yml
...

Style: (ID tocW_02): More than 1 ordered list in a numbered clause

Render Init: 15:55:30
Error: cannot load such file -- metanorma-handbook
Metanorma has encountered an exception.

If this problem persists, please report this issue at the following link:

* https://github.com/metanorma/metanorma/issues/new

Please attach the 2024-10-08-error.log file.
Your valuable feedback is very much appreciated!

- The Metanorma team
```

Notice that it says:
```
Error: cannot load such file -- metanorma-handbook
```

Clearly the bibdata wasn't correct (well what the keys mean are very unclear), and Metanorma should have validated its input before doing any compilation, because the result will be a fail.

This task is to bring collection.yml validation to the first step of collection processing.
