### ISSUE TITLE
(URGENT) metanorma collection not generating RXL files

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma#434]
From:
* https://github.com/metanorma/itu-contribution-samples/issues/2

Every collection provides bibliographic data. However, the generated collection does not produce an RXL file.

The collection.yml looks like this:
```yaml
directives:
  - documents-inline
  - collection-word-coverpage: null
  - collection-word-intropage: null
  - document-word-coverpage: ""
  - document-word-intropage: "itu_embedded_intro.html"
bibdata:
  title:
    - language: en
      content: "Sample ITU contribution"
  type: collection
  docid:
    type: ITU
    id: SG17-C660
  copyright:
    owner:
      name: International Telecommunications Union
      abbreviation: ITU
    from: 2019
format:
  - presentation
  - html
  - pdf
  - doc
  - rxl                         # << THIS LINE IS PRESENT
output_folder: contribution-new-item
manifest:
  level: document
  title: Document
  docref:
    - fileref: document.adoc
      identifier: SG17-C660
    - fileref: target.adoc
      identifier: ITU G.650
```

```sh
$ bundle exec metanorma collection sources/contribution-new-item/collection.yml
...
$ ls -al contribution-new-item
collection.doc
collection.pdf
collection.pdf.err
collection.presentation.xml
document.doc
document.err.html
document.html
document.pdf
document.pdf.err
document.pdf.pdf_fonts_config.xml.out
document.presentation.xml
document.rxl
document20241221-38358-bp4797.xml_tmp
target.doc
target.err.html
target.html
target.pdf
target.pdf.err
target.presentation.xml
target.rxl
```

`collection.rxl` is missing.
