### ISSUE TITLE
(URGENT) metanorma collection should generate output at a path relative to itself, not PWD

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma#435]
From:
* https://github.com/metanorma/itu-contribution-samples/issues/3

There is a collection option for `output_folder`, however, the generated files from `metanorma collection` are located at `$PWD/{output_folder}` not `{path of collection.yml}/{output_folder}`, which is inconsistent with the `metanorma compile` output being at the same place as `{path of document.adoc}.{extension}` not at `$PWD`.

The collection.yml looks like this:
```yaml
directives:
  - documents-inline
  - collection-word-coverpage: null
  - collection-word-intropage: null
  - document-word-coverpage: ""
  - document-word-intropage: "itu_embedded_intro.html"
bibdata:
  title:
    - language: en
      content: "Sample ITU contribution"
  type: collection
  docid:
    type: ITU
    id: SG17-C660
  copyright:
    owner:
      name: International Telecommunications Union
      abbreviation: ITU
    from: 2019
format:
  - presentation
  - html
  - pdf
  - doc
  - rxl
output_folder: contribution-new-item       # << THIS LINE PRESENT
manifest:
  level: document
  title: Document
  docref:
    - fileref: document.adoc
      identifier: SG17-C660
    - fileref: target.adoc
      identifier: ITU G.650
```

```sh
$ bundle exec metanorma collection sources/contribution-new-item/collection.yml
...
$ ls -al sources/contribution-new-item/contribution-new-item
# NOT FOUND!!

$ ls -al contribution-new-item
collection.doc
collection.pdf
collection.pdf.err
collection.presentation.xml
document.doc
document.err.html
document.html
document.pdf
document.pdf.err
document.pdf.pdf_fonts_config.xml.out
document.presentation.xml
document.rxl
document20241221-38358-bp4797.xml_tmp
target.doc
target.err.html
target.html
target.pdf
target.pdf.err
target.presentation.xml
target.rxl
```
