### ISSUE TITLE
(URGENT) metanorma site generate command not loading generated collection files

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma#436]
From:
* https://github.com/metanorma/itu-contribution-samples/issues/4

The `metanorma.yml` file looks like this:

```yaml
---
metanorma:
  source:
    files:
      - sources/contribution-generic/document.adoc
      - sources/contribution-new-item/collection.yml
      - sources/contribution-revision/collection.yml

  collection:
    organization: "International Telecommunications Union"
    name: "ITU-T Contribution samples"
```

However, running `site generate` it does not find the collection-generated files:

```sh
$ bundle exec metanorma site generate
...
$ ls -al _site
contribution-new-item/
contribution-revision/
documents/
documents.xml
index.html
```

But `index.html` can only see the document at `sources/contribution-generic/document.adoc`.

<img width="650" alt="Screenshot 2024-12-21 at 11 06 37 AM" src="https://github.com/user-attachments/assets/4b8502cf-ce9a-4d0c-b843-cb00996c3217" />

This may be dependent on:
* [ ] #2
