### ISSUE TITLE
Use consistent Travis configuration files across gems and documents

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma#48]
Originally from https://github.com/metanorma/unicode2latex/pull/3

This issue is to apply the same Travis configuration across:

* Metanorma gems
* Metanorma gems (with atypical dependencies, e.g. external tools)
* Metanorma documents

---

Original discussion:

> But I think we have more then 2 types, because some of gem required xml2rfx, pupeeteer, plantuml

Yes. Those are the outliers that we have to handle separately.

> 'plain' gem
> gem with external tools
> individual docs

Agree.

> Looks like no way https://stackoverflow.com/questions/44108837/sharing-travis-configuration-among-multiple-repositories but let me check official documentation

Right, but we can use a common `.travis.yml` from a common place (e.g. `metanorma-build-scripts`).

Can you help proceed? Thanks!

**Comment by CAMOBAP795** [comment]
> Right, but we can use a common .travis.yml from a common place (e.g. metanorma-build-scripts).

I'm not sure about this, but https://github.com/travis-ci/travis.rb can help us to manage configuration

Anyway let me first finish #46 I will see whole picture once it will be done

**Comment by CAMOBAP795** [comment]
### Research

I have finished the research and looks like there is no existing solution for this:
 - no way to keep `.travis.yml` config
 - no way to use `travis.rb` to modify all repositories at once (master script need to be written for this)

### Proposed solution

The only solution which I see right now is to create configuration based on `repo` tool https://gerrit.googlesource.com/git-repo/ :
0. Use https://github.com/metanorma/metanorma-build-scripts as repo to keep configuration
1. This repo will contains master copies for `travis.yml` and `appveyour.yml` configurations
1. Create Manifest with all repos which are used CI
2. Create configuration (simple yml, json or xml) called `ci.yml`. which keep a relation between repository and master `travis.yml` and `appveyour.yml` config file for it from https://github.com/metanorma/metanorma-build-scripts
3. Write simple script `sync.rb` (on bash/ruby/python) which will perform 'synchronization' (or propogation) of travis/appveyor config from https://github.com/metanorma/metanorma-build-scripts to target repository
4. This script will create PR

#### Possible`ci.yml` config format
```yml
repos:
  - metanorma/metanorma-cli
    - appveyor.yml: appveyor/appveyor.v2.yml
    - .travis.yml: travis/travis.v5.yml
  - metanorma/metanorma
     - appveyor.yml: appveyor/appveyor.v1.yml
     - .travis.yml: travis/travis.v0.yml
  - ... # another repos
settings:
  force-push: false # push without PR
  ... # anothe settings
```

### Workflow (possible for different use cases)

#### Case 1: Update travis.yml for all repos

1. Update all `travis.yml`s in https://github.com/metanorma/metanorma-build-scripts
2. Run script to create PR for each repo which will be modified

#### Case 2: Modif travis.yml for single repo

1. Create separate  `travis.yml` or `appveyour.yml`
2. Update `ci.yml` to point to this new file
3. Run script to create PR for each repo which will be modified

#### Case 3: Remove from CI

1. Delete repository entry from `ci.yml`
2. Run script to create PR for each repo which will be modified
